name: Update Repository

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- run: git config --global user.email "ci@fuchss.org" && git config --global user.name "GitHub CI"
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Init Repository Secrets
        run: echo $KEYSTORE_FILE | base64 --decode > fdroid/keystore.p12
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      
      - name: Update F-Droid Repo
        run: |
          docker run --rm -u $UID -v $GITHUB_WORKSPACE/fdroid:/repo registry.gitlab.com/fdroid/docker-executable-fdroidserver:master rewritemeta
          docker run --rm -u $UID -v $GITHUB_WORKSPACE/fdroid:/repo registry.gitlab.com/fdroid/docker-executable-fdroidserver:master update --create-metadata
        env:
          KEYDNAME: ${{ secrets.KEYDNAME }}
          KEYPASS: ${{ secrets.KEYPASS }}
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_FILENAME: ${{ secrets.KEYSTORE_FILENAME }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS}}
          REPO_KEYALIAS: ${{ secrets.REPO_KEYALIAS }} 
      # - name: Build the directory for github pages
      #   run: |
      #     mkdir -p pages_output
      #     cp -r fdroid/repo pages_output
      #     cp -r fdroid/archive pages_output/
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: fdroid/repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- run: cd fdroid && git add . && git commit -m "Update from $GITHUB_SHA" && git push origin fdroid